# -*- coding: utf-8 -*-
"""Pandas Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l_LPHCzaoqsENuC9ol__3l8Rbsn_LGpx
"""

# Import the necessary libraries
import pandas as pd

# Assign it to a variable called users and use the 'user_id' as index

users = pd.read_table('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', 
                      sep='|', index_col='user_id')
users

# See the first 10 and last 10 entries
users.head(10)

users.tail(10)

#What is the number of observations in the dataset?

users.shape[0]

#What is the number of columns in the dataset?
users.shape[1]

#Print the name of all the columns.
users.columns

#How is the dataset indexed?
users.index

#What is the data type of each column?
users.dtypes

#Print only the occupation column
users.occupation    
#OR
users['occupation']

#How many different occupations are in this dataset?

len(users.occupation.unique())

#What is the most frequent occupation?
users['occupation'].mode()

#DataFrame Info.
users.info()

#Describe all the columns

users.describe(include = "all")

#Summarize only the occupation column
users.occupation.describe()

#What is the mean age of users?
users['age'].mean()

#What is the age with least occurrence?
users['age'].value_counts().tail().head(1)